//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casamia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DESIGN_SVN_DEPTH {
            get {
                return ((int)(this["DESIGN_SVN_DEPTH"]));
            }
            set {
                this["DESIGN_SVN_DEPTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FURNITURE_SVN_DEPTH {
            get {
                return ((int)(this["FURNITURE_SVN_DEPTH"]));
            }
            set {
                this["FURNITURE_SVN_DEPTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("workspace.config")]
        public string WORKSPACE_CONFIG_PATH {
            get {
                return ((string)(this["WORKSPACE_CONFIG_PATH"]));
            }
            set {
                this["WORKSPACE_CONFIG_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%SELECTED_PROJECT%")]
        public string SELECTED_PROJECT_PLACEHOLDER {
            get {
                return ((string)(this["SELECTED_PROJECT_PLACEHOLDER"]));
            }
            set {
                this["SELECTED_PROJECT_PLACEHOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%SELECTED_PROJECT_URL%")]
        public string SELECTED_PROJECT_URL_PLACEHOLDER {
            get {
                return ((string)(this["SELECTED_PROJECT_URL_PLACEHOLDER"]));
            }
            set {
                this["SELECTED_PROJECT_URL_PLACEHOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("executors.config")]
        public string EXECUTOR_CONFIG_PATH {
            get {
                return ((string)(this["EXECUTOR_CONFIG_PATH"]));
            }
            set {
                this["EXECUTOR_CONFIG_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[
	{
		""Description"" : ""Checkout Project"",
		""Name"" : ""CheckoutProject"",
		""ID"" : 0,
		""commandList"" : [
			{
				""Executor"" : ""%EXE_APP_SVN%"",
				""Status"" : 0,
				""Argument"" : ""checkout %SELECTED_PROJECT_URL% \""%SELECTED_PROJECT%\"""",
				""Timeout"" : ""-00:00:01"",
				""Description"" : ""Checkout project.""
			}
		],
		""Status"" : 0
	},
	{
		""Description"" : ""SVN diff "",
		""Name"" : ""SVN_DIFF_TASK"",
		""ID"" : 0,
		""commandList"" : [
			{
				""Executor"" : ""%EXE_APP_SVN%"",
				""Status"" : 0,
				""Argument"" : ""diff  \""%SELECTED_PROJECT%\"""",
				""Timeout"" : ""-00:00:01"",
				""Description"" : ""Svn diff.""
			}
		],
		""Status"" : 0
	},
	{
		""Description"" : ""SVN list "",
		""Name"" : ""SVN_LIST_TASK"",
		""ID"" : 0,
		""commandList"" : [
			{
				""Executor"" : ""%EXE_APP_SVN%"",
				""Status"" : 0,
				""Argument"" : ""list  %SELECTED_PROJECT_URL%"",
				""Timeout"" : ""-00:00:01"",
				""Description"" : ""Svn list.""
			}
		],
		""Status"" : 0
	}
]
")]
        public string EMBEDDED_TASKS {
            get {
                return ((string)(this["EMBEDDED_TASKS"]));
            }
            set {
                this["EMBEDDED_TASKS"] = value;
            }
        }
    }
}
